name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['10.x']

    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up MariaDB 10
      uses: getong/mariadb-action@v1.3
      with:
        mariadb version: 10.4.10
        mysql database: test
        mysql root password: ${{ secrets.DatabasePassword }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm test -- --password=${{ secrets.DatabasePassword }}
      env:
        CI: true
