name: test

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['10.x']
        mariadb-version:
          - 10.4.10
          - 10.6
          - 11.4

    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up MariaDB ${{ matrix.mariadb-version }}
      uses: ./
      with:
        mariadb version: ${{ matrix.mariadb-version }}
        mysql database: test
        mysql root password: ${{ secrets.DatabasePassword }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm test -- --password=${{ secrets.DatabasePassword }}
      env:
        CI: true
